<Project>
  <Target Name="EnsureFullGitHistoryForNbgv" BeforeTargets="GetBuildVersionCore">
    <Exec Command="git rev-parse --is-shallow-repository" WorkingDirectory="$(GitVersionBaseDirectory)" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="_IsShallowRepositoryRaw" />
    </Exec>
    <PropertyGroup>
      <_IsShallowRepository>$([System.String]::Copy('$(_IsShallowRepositoryRaw)').Trim())</_IsShallowRepository>
    </PropertyGroup>
    <Exec Condition=" '$(_IsShallowRepository)' == 'true' " Command="git fetch --prune --tags --unshallow" WorkingDirectory="$(GitVersionBaseDirectory)" IgnoreExitCode="false" />
  </Target>
</Project>
