<Project>
  <!-- NerdBank.GitVersioning for all projects -->
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.8.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>